number = input("номер рейса: ")
company_name_ru = input("название авиакомпании(на русском языке): ")
company_name_en = input("название авиакомпании(на английском языке): ")
city_ru = input("город прилета(на русском языке): ")
city_en = input("город прилета(на английском языке): ")
print(f"Заканчивается посадка на рейс {number} {company_name_ru} до {city_ru}")
print(f"This is the final boarding call for {company_name_en} fligth {number} to {city_en}")
