print("Введите плей-лист папы:")
song_1 = input()
song_2 = input()
song_3 = input()
song_4 = input()
song_5 = input()
print(f"Плей-лист мамы: \n{song_5} \n{song_4} \n{song_3} \n{song_2} \n{song_1} ")
